const programs = [
  "Accounting and Related Services.",
  "Aerospace, Aeronautical and Astronautical Engineering.",
  "Agricultural Business and Management.",
  "Agricultural Engineering.",
  "Agricultural Mechanization.",
  "Agricultural Production Operations.",
  "Agricultural Public Services.",
  "Agricultural and Domestic Animal Services.",
  "Agricultural and Food Products Processing.",
  "Agriculture, Agriculture Operations, and Related Sciences, Other.",
  "Agriculture, General.",
  "Agriculture/Veterinary Preparatory Programs.",
  "Air Transportation.",
  "Allied Health Diagnostic, Intervention, and Treatment Professions.",
  "Allied Health and Medical Assisting Services.",
  "Alternative and Complementary Medical Support Services.",
  "Alternative and Complementary Medicine and Medical Systems.",
  "American Sign Language.",
  "Animal Sciences.",
  "Anthropology.",
  "Apparel and Textiles.",
  "Applied Horticulture and Horticultural Business Services.",
  "Applied Mathematics.",
  "Archeology.",
  "Architectural Engineering Technologies/Technicians.",
  "Architectural Engineering.",
  "Architectural History and Criticism.",
  "Architectural Sciences and Technology.",
  "Architecture and Related Services, Other.",
  "Architecture.",
  "Area Studies.",
  "Arts, Entertainment,and Media Management.",
  "Astronomy and Astrophysics.",
  "Atmospheric Sciences and Meteorology.",
  "Audiovisual Communications Technologies/Technicians.",
  "Behavioral Sciences.",
  "Bible/Biblical Studies.",
  "Bilingual, Multilingual, and Multicultural Education.",
  "Biochemical Engineering.",
  "Biochemistry, Biophysics and Molecular Biology.",
  "Bioethics/Medical Ethics.",
  "Biological and Biomedical Sciences, Other.",
  "Biological and Physical Sciences.",
  "Biological/Biosystems Engineering.",
  "Biology Technician/Biotechnology Laboratory Technician.",
  "Biology, General.",
  "Biomathematics, Bioinformatics, and Computational Biology.",
  "Biomedical/Medical Engineering.",
  "Biopsychology.",
  "Biotechnology.",
  "Building/Construction Finishing, Management, and Inspection.",
  "Business Administration, Management and Operations.",
  "Business Operations Support and Assistant Services.",
  "Business, Management, Marketing, and Related Support Services, Other.",
  "Business/Commerce, General.",
  "Business/Corporate Communications.",
  "Business/Managerial Economics.",
  "Cell/Cellular Biology and Anatomical Sciences.",
  "Ceramic Sciences and Engineering.",
  "Chemical Engineering.",
  "Chemistry.",
  "City/Urban, Community and Regional Planning.",
  "Civil Engineering Technologies/Technicians.",
  "Civil Engineering.",
  "Classical and Ancient Studies.",
  "Classics and Classical Languages, Literatures, and Linguistics.",
  "Clinical, Counseling and Applied Psychology.",
  "Clinical/Medical Laboratory Science/Research and Allied Professions.",
  "Cognitive Science.",
  "Communication Disorders Sciences and Services.",
  "Communication and Media Studies.",
  "Communication, Journalism, and Related Programs, Other.",
  "Communications Technologies/Technicians and Support Services, Other.",
  "Communications Technology/Technician.",
  "Community Organization and Advocacy.",
  "Computational Science.",
  "Computer Engineering Technologies/Technicians.",
  "Computer Engineering.",
  "Computer Programming.",
  "Computer Science.",
  "Computer Software and Media Applications.",
  "Computer Systems Analysis.",
  "Computer Systems Networking and Telecommunications.",
  "Computer and Information Sciences and Support Services, Other.",
  "Computer and Information Sciences, General.",
  "Computer/Information Technology Administration and Management.",
  "Construction Engineering Technologies.",
  "Construction Engineering.",
  "Construction Management.",
  "Construction Trades, Other.",
  "Cosmetology and Related Personal Grooming Services.",
  "Crafts/Craft Design, Folk Art and Artisanry.",
  "Criminal Justice and Corrections.",
  "Criminology.",
  "Culinary Arts and Related Services.",
  "Cultural Studies/Critical Theory and Analysis.",
  "Curriculum and Instruction.",
  "Dance.",
  "Data Processing.",
  "Dental Support Services and Allied Professions.",
  "Design and Applied Arts.",
  "Dietetics and Clinical Nutrition Services.",
  "Drafting/Design Engineering Technologies/Technicians.",
  "Drama/Theatre Arts and Stagecraft.",
  "East Asian Languages, Literatures, and Linguistics.",
  "Ecology, Evolution, Systematics, and Population Biology.",
  "Economics.",
  "Education, General.",
  "Education, Other.",
  "Educational Assessment, Evaluation, and Research.",
  "Educational/Instructional Media Design.",
  "Electrical Engineering Technologies/Technicians.",
  "Electrical, Electronics and Communications Engineering.",
  "Electromechanical Engineering.",
  "Electromechanical Instrumentation and Maintenance Technologies/Technicians.",
  "Energy Systems Technologies/Technicians.",
  "Energy and Biologically Based Therapies.",
  "Engineering Mechanics.",
  "Engineering Physics.",
  "Engineering Science.",
  "Engineering Technologies/Technicians, Other.",
  "Engineering Technology, General.",
  "Engineering, General.",
  "Engineering, Other.",
  "Engineering-Related Fields.",
  "Engineering-Related Technologies.",
  "English Language and Literature, General.",
  "English Language and Literature/Letters, Other.",
  "Entrepreneurial and Small Business Operations.",
  "Environmental Control Technologies/Technicians.",
  "Environmental Design.",
  "Environmental/Environmental Health Engineering.",
  "Ethnic, Cultural Minority, Gender, and Group Studies.",
  "Family and Consumer Economics and Related Studies.",
  "Family and Consumer Sciences/Human Sciences Business Services.",
  "Family and Consumer Sciences/Human Sciences, General.",
  "Family and Consumer Sciences/Human Sciences, Other.",
  "Film/Video and Photographic Arts.",
  "Finance and Financial Management Services.",
  "Fine and Studio Arts.",
  "Fire Protection.",
  "Fishing and Fisheries Sciences and Management.",
  "Food Science and Technology.",
  "Foods, Nutrition, and Related Services.",
  "Foreign Languages, Literatures, and Linguistics, Other.",
  "Forest Engineering.",
  "Forestry.",
  "Funeral Service and Mortuary Science.",
  "General Sales, Merchandising and Related Marketing Operations.",
  "Genetics.",
  "Geography and Cartography.",
  "Geological and Earth Sciences/Geosciences.",
  "Germanic Languages, Literatures, and Linguistics.",
  "Gerontology.",
  "Graphic Communications.",
  "Health Professions and Related Clinical Sciences, Other.",
  "Health Services/Allied Health/Health Sciences, General.",
  "Health and Medical Administrative Services.",
  "Health and Physical Education/Fitness.",
  "Health-Related Knowledge and Skills.",
  "Health/Medical Preparatory Programs.",
  "Heavy/Industrial Equipment Maintenance Technologies.",
  "Historic Preservation and Conservation.",
  "History.",
  "Holocaust and Related Studies.",
  "Homeland Security, Law Enforcement, Firefighting and Related Protective Services, Other.",
  "Homeland Security.",
  "Hospitality Administration/Management.",
  "Housing and Human Environments.",
  "Human Biology.",
  "Human Computer Interaction.",
  "Human Development, Family Studies, and Related Services.",
  "Human Resources Management and Services.",
  "Human Services, General.",
  "Industrial Engineering.",
  "Industrial Production Technologies/Technicians.",
  "Information Science/Studies.",
  "Insurance.",
  "Intercultural/Multicultural and Diversity Studies.",
  "Interior Architecture.",
  "International Agriculture.",
  "International Business.",
  "International Relations and National Security Studies.",
  "International and Comparative Education.",
  "International/Global Studies.",
  "Journalism.",
  "Landscape Architecture.",
  "Legal Professions and Studies, Other.",
  "Legal Research and Advanced Professional Studies.",
  "Legal Support Services.",
  "Leisure and Recreational Activities.",
  "Liberal Arts and Sciences, General Studies and Humanities.",
  "Linguistic, Comparative, and Related Language Studies and Services.",
  "Literature.",
  "Management Information Systems and Services.",
  "Management Sciences and Quantitative Methods.",
  "Manufacturing Engineering.",
  "Marine Sciences.",
  "Marine Transportation.",
  "Marketing.",
  "Materials Engineering",
  "Materials Sciences.",
  "Mathematics and Statistics, Other.",
  "Mathematics.",
  "Mechanical Engineering Related Technologies/Technicians.",
  "Mechanical Engineering.",
  "Mechatronics, Robotics, and Automation Engineering.",
  "Medical Illustration and Informatics.",
  "Mental and Social Health Services and Allied Professions.",
  "Microbiological Sciences and Immunology.",
  "Middle/Near Eastern and Semitic Languages, Literatures, and Linguistics.",
  "Mining and Petroleum Technologies/Technicians.",
  "Missions/Missionary Studies and Missiology.",
  "Movement and Mind-Body Therapies and Education.",
  "Multi-/Interdisciplinary Studies, General.",
  "Multi/Interdisciplinary Studies, Other.",
  "Music.",
  "Natural Resources Conservation and Research.",
  "Natural Resources Management and Policy.",
  "Natural Resources and Conservation, Other.",
  "Natural Sciences.",
  "Naval Architecture and Marine Engineering.",
  "Neurobiology and Neurosciences.",
  "Non-Professional General Legal Studies (Undergraduate).",
  "Nuclear Engineering Technologies/Technicians.",
  "Nuclear Engineering.",
  "Nursing.",
  "Nutrition Sciences.",
  "Ocean Engineering.",
  "Operations Research.",
  "Outdoor Education.",
  "Parks, Recreation and Leisure Facilities Management.",
  "Parks, Recreation and Leisure Studies.",
  "Parks, Recreation, Leisure, and Fitness Studies, Other.",
  "Pastoral Counseling and Specialized Ministries.",
  "Peace Studies and Conflict Resolution.",
  "Petroleum Engineering.",
  "Pharmacy, Pharmaceutical Sciences, and Administration.",
  "Philosophy and Religious Studies, General.",
  "Philosophy and Religious Studies, Other.",
  "Philosophy.",
  "Physics.",
  "Physiology, Pathology and Related Sciences.",
  "Plant Sciences.",
  "Political Science and Government.",
  "Polymer/Plastics Engineering.",
  "Practical Nursing, Vocational Nursing and Nursing Assistants.",
  "Program name",
  "Psychology, General.",
  "Psychology, Other.",
  "Public Administration and Social Service Professions, Other.",
  "Public Administration.",
  "Public Health.",
  "Public Policy Analysis.",
  "Public Relations, Advertising, and Applied Communication.",
  "Quality Control and Safety Technologies/Technicians.",
  "Radio, Television, and Digital Communication.",
  "Real Estate.",
  "Registered Nursing, Nursing Administration, Nursing Research and Clinical Nursing.",
  "Rehabilitation and Therapeutic Professions.",
  "Religion/Religious Studies.",
  "Religious Education.",
  "Religious/Sacred Music.",
  "Research and Experimental Psychology.",
  "Rhetoric and Composition/Writing Studies.",
  "Romance Languages, Literatures, and Linguistics.",
  "Science Technologies/Technicians, General.",
  "Science Technologies/Technicians, Other.",
  "Science, Technology and Society.",
  "Security Science and Technology.",
  "Slavic, Baltic and Albanian Languages, Literatures, and Linguistics.",
  "Social Sciences, General.",
  "Social Sciences, Other.",
  "Social Work.",
  "Social and Philosophical Foundations of Education.",
  "Sociology and Anthropology.",
  "Sociology.",
  "Somatic Bodywork and Related Therapeutic Services.",
  "Special Education and Teaching.",
  "Specialized Sales, Merchandising and  Marketing Operations.",
  "Statistics.",
  "Surveying Engineering.",
  "Sustainability Studies.",
  "Systems Engineering.",
  "Systems Science and Theory.",
  "Teacher Education and Professional Development, Specific Levels and Methods.",
  "Teacher Education and Professional Development, Specific Subject Areas.",
  "Teaching English or French as a Second or Foreign Language.",
  "Textile Sciences and Engineering.",
  "Theological and Ministerial Studies.",
  "Theology and Religious Vocations, Other.",
  "Transportation and Materials Moving, Other.",
  "Urban Studies/Affairs.",
  "Vehicle Maintenance and Repair Technologies.",
  "Veterinary Biomedical and Clinical Sciences.",
  "Veterinary Medicine.",
  "Veterinary/Animal Health Technologies/Technicians.",
  "Visual and Performing Arts, General.",
  "Visual and Performing Arts, Other.",
  "Wildlife and Wildlands Science and Management.",
  "Zoology/Animal Biology.",
];
export default programs;
