/* tslint:disable */
/* eslint-disable */
//  This file was automatically generated and should not be edited.

export type CreateUserInfoInput = {
  id?: string | null,
  email?: string | null,
  dayPreferences?: string | null,
  timePreferences?: string | null,
  location?: string | null,
  modalityPreferences?: string | null,
  userType?: string | null,
  viewHistory?: string | null,
  searchHistory?: string | null,
  _version?: number | null,
};

export type ModelUserInfoConditionInput = {
  email?: ModelStringInput | null,
  dayPreferences?: ModelStringInput | null,
  timePreferences?: ModelStringInput | null,
  location?: ModelStringInput | null,
  modalityPreferences?: ModelStringInput | null,
  userType?: ModelStringInput | null,
  viewHistory?: ModelStringInput | null,
  searchHistory?: ModelStringInput | null,
  and?: Array< ModelUserInfoConditionInput | null > | null,
  or?: Array< ModelUserInfoConditionInput | null > | null,
  not?: ModelUserInfoConditionInput | null,
};

export type ModelStringInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  size?: ModelSizeInput | null,
};

export enum ModelAttributeTypes {
  binary = "binary",
  binarySet = "binarySet",
  bool = "bool",
  list = "list",
  map = "map",
  number = "number",
  numberSet = "numberSet",
  string = "string",
  stringSet = "stringSet",
  _null = "_null",
}


export type ModelSizeInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
};

export type UserInfo = {
  __typename: "UserInfo",
  id: string,
  email?: string | null,
  dayPreferences?: string | null,
  timePreferences?: string | null,
  location?: string | null,
  modalityPreferences?: string | null,
  userType?: string | null,
  viewHistory?: string | null,
  searchHistory?: string | null,
  createdAt: string,
  updatedAt: string,
  _version: number,
  _deleted?: boolean | null,
  _lastChangedAt: number,
  owner?: string | null,
};

export type UpdateUserInfoInput = {
  id: string,
  email?: string | null,
  dayPreferences?: string | null,
  timePreferences?: string | null,
  location?: string | null,
  modalityPreferences?: string | null,
  userType?: string | null,
  viewHistory?: string | null,
  searchHistory?: string | null,
  _version?: number | null,
};

export type DeleteUserInfoInput = {
  id: string,
  _version?: number | null,
};

export type CreateROIInput = {
  id?: string | null,
  uniqueId?: string | null,
  institutionName?: string | null,
  programName?: string | null,
  unitId?: number | null,
  stateFIPSCode?: number | null,
  programCIPCode?: number | null,
  programCategory?: string | null,
  control?: string | null,
  carnegieClassification2015?: string | null,
  admissionsRate?: number | null,
  credentialLevel?: number | null,
  credentialLevelDescription?: string | null,
  collegeScorecardCohortCount?: number | null,
  annualNetTuitionCost?: number | null,
  fourYearNetTuitionCost?: number | null,
  annualEducationRelatedSpending?: number | null,
  shareOfStudentWhoGraduateIn4Years?: number | null,
  shareOfStudentWhoGraduateIn5Years?: number | null,
  shareOfStudentWhoGraduateIn6Years?: number | null,
  shareOfStudentWhoTransferOutIn6Years?: number | null,
  shareOfStudentWhoRemainIn6Years?: number | null,
  shareOfStudentWhoNoLongerEnrolledIn6Years?: number | null,
  absoluteIncreaseInLifetimeEarnings?: number | null,
  percentageIncreaseInLifetimeEarnings?: string | null,
  lifetimeReturnOnInvestmentROI?: number | null,
  ageAtWhichROITurnsPositive?: number | null,
  rankOfProgramByROI?: number | null,
  ROIIfStudentTakes5YearsToGraduate?: number | null,
  ROIIfStudentTakes6YearsToGraduate?: number | null,
  ROIIfStudentDropsBeforeGraduating?: number | null,
  ROIWeightedByInstitutionsCompletionOutcomes?: number | null,
  ROIBasedOnInstitutionsEducationRelatedSpending?: number | null,
  ROIBasedOnInstitutionsEducationRelatedSpending5years?: number | null,
  ROIBasedOnInstitutionsEducationRelatedSpending6Years?: number | null,
  ROIBasedOnInstitutionsEducationRelatedSpendingDrops?: number | null,
  ROIBasedOnInstitutionsEducationRelatedSpendingCompletionOutcomes?: number | null,
  estimatedEarnings23?: number | null,
  estimatedEarnings26?: number | null,
  estimatedEarnings29?: number | null,
  estimatedEarnings32?: number | null,
  estimatedEarnings35?: number | null,
  estimatedEarnings38?: number | null,
  estimatedEarnings41?: number | null,
  estimatedEarnings44?: number | null,
  estimatedEarnings47?: number | null,
  estimatedEarnings50?: number | null,
  estimatedEarnings53?: number | null,
  estimatedEarnings56?: number | null,
  estimatedEarnings59?: number | null,
  estimatedEarnings62?: number | null,
  estimatedCounterfactualEarnings19?: number | null,
  estimatedCounterfactualEarnings21?: number | null,
  estimatedCounterfactualEarnings23?: number | null,
  estimatedCounterfactualEarnings26?: number | null,
  estimatedCounterfactualEarnings29?: number | null,
  estimatedCounterfactualEarnings32?: number | null,
  estimatedCounterfactualEarnings35?: number | null,
  estimatedCounterfactualEarnings38?: number | null,
  estimatedCounterfactualEarnings41?: number | null,
  estimatedCounterfactualEarnings44?: number | null,
  estimatedCounterfactualEarnings47?: number | null,
  estimatedCounterfactualEarnings50?: number | null,
  estimatedCounterfactualEarnings53?: number | null,
  estimatedCounterfactualEarnings56?: number | null,
  estimatedCounterfactualEarnings59?: number | null,
  estimatedCounterfactualEarnings62?: number | null,
  resultsAvailableForAllSpecifications?: number | null,
  fourYearEducationRelatedSpending?: number | null,
  state?: string | null,
  _version?: number | null,
};

export type ModelROIConditionInput = {
  uniqueId?: ModelStringInput | null,
  institutionName?: ModelStringInput | null,
  programName?: ModelStringInput | null,
  unitId?: ModelIntInput | null,
  stateFIPSCode?: ModelIntInput | null,
  programCIPCode?: ModelIntInput | null,
  programCategory?: ModelStringInput | null,
  control?: ModelStringInput | null,
  carnegieClassification2015?: ModelStringInput | null,
  admissionsRate?: ModelIntInput | null,
  credentialLevel?: ModelIntInput | null,
  credentialLevelDescription?: ModelStringInput | null,
  collegeScorecardCohortCount?: ModelIntInput | null,
  annualNetTuitionCost?: ModelIntInput | null,
  fourYearNetTuitionCost?: ModelIntInput | null,
  annualEducationRelatedSpending?: ModelIntInput | null,
  shareOfStudentWhoGraduateIn4Years?: ModelFloatInput | null,
  shareOfStudentWhoGraduateIn5Years?: ModelFloatInput | null,
  shareOfStudentWhoGraduateIn6Years?: ModelFloatInput | null,
  shareOfStudentWhoTransferOutIn6Years?: ModelFloatInput | null,
  shareOfStudentWhoRemainIn6Years?: ModelFloatInput | null,
  shareOfStudentWhoNoLongerEnrolledIn6Years?: ModelFloatInput | null,
  absoluteIncreaseInLifetimeEarnings?: ModelIntInput | null,
  percentageIncreaseInLifetimeEarnings?: ModelStringInput | null,
  lifetimeReturnOnInvestmentROI?: ModelIntInput | null,
  ageAtWhichROITurnsPositive?: ModelIntInput | null,
  rankOfProgramByROI?: ModelIntInput | null,
  ROIIfStudentTakes5YearsToGraduate?: ModelIntInput | null,
  ROIIfStudentTakes6YearsToGraduate?: ModelIntInput | null,
  ROIIfStudentDropsBeforeGraduating?: ModelIntInput | null,
  ROIWeightedByInstitutionsCompletionOutcomes?: ModelIntInput | null,
  ROIBasedOnInstitutionsEducationRelatedSpending?: ModelIntInput | null,
  ROIBasedOnInstitutionsEducationRelatedSpending5years?: ModelIntInput | null,
  ROIBasedOnInstitutionsEducationRelatedSpending6Years?: ModelIntInput | null,
  ROIBasedOnInstitutionsEducationRelatedSpendingDrops?: ModelIntInput | null,
  ROIBasedOnInstitutionsEducationRelatedSpendingCompletionOutcomes?: ModelIntInput | null,
  estimatedEarnings23?: ModelIntInput | null,
  estimatedEarnings26?: ModelIntInput | null,
  estimatedEarnings29?: ModelIntInput | null,
  estimatedEarnings32?: ModelIntInput | null,
  estimatedEarnings35?: ModelIntInput | null,
  estimatedEarnings38?: ModelIntInput | null,
  estimatedEarnings41?: ModelIntInput | null,
  estimatedEarnings44?: ModelIntInput | null,
  estimatedEarnings47?: ModelIntInput | null,
  estimatedEarnings50?: ModelIntInput | null,
  estimatedEarnings53?: ModelIntInput | null,
  estimatedEarnings56?: ModelIntInput | null,
  estimatedEarnings59?: ModelIntInput | null,
  estimatedEarnings62?: ModelIntInput | null,
  estimatedCounterfactualEarnings19?: ModelIntInput | null,
  estimatedCounterfactualEarnings21?: ModelIntInput | null,
  estimatedCounterfactualEarnings23?: ModelIntInput | null,
  estimatedCounterfactualEarnings26?: ModelIntInput | null,
  estimatedCounterfactualEarnings29?: ModelIntInput | null,
  estimatedCounterfactualEarnings32?: ModelIntInput | null,
  estimatedCounterfactualEarnings35?: ModelIntInput | null,
  estimatedCounterfactualEarnings38?: ModelIntInput | null,
  estimatedCounterfactualEarnings41?: ModelIntInput | null,
  estimatedCounterfactualEarnings44?: ModelIntInput | null,
  estimatedCounterfactualEarnings47?: ModelIntInput | null,
  estimatedCounterfactualEarnings50?: ModelIntInput | null,
  estimatedCounterfactualEarnings53?: ModelIntInput | null,
  estimatedCounterfactualEarnings56?: ModelIntInput | null,
  estimatedCounterfactualEarnings59?: ModelIntInput | null,
  estimatedCounterfactualEarnings62?: ModelIntInput | null,
  resultsAvailableForAllSpecifications?: ModelIntInput | null,
  fourYearEducationRelatedSpending?: ModelIntInput | null,
  state?: ModelStringInput | null,
  and?: Array< ModelROIConditionInput | null > | null,
  or?: Array< ModelROIConditionInput | null > | null,
  not?: ModelROIConditionInput | null,
};

export type ModelIntInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
};

export type ModelFloatInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
};

export type ROI = {
  __typename: "ROI",
  id: string,
  uniqueId?: string | null,
  institutionName?: string | null,
  programName?: string | null,
  unitId?: number | null,
  stateFIPSCode?: number | null,
  programCIPCode?: number | null,
  programCategory?: string | null,
  control?: string | null,
  carnegieClassification2015?: string | null,
  admissionsRate?: number | null,
  credentialLevel?: number | null,
  credentialLevelDescription?: string | null,
  collegeScorecardCohortCount?: number | null,
  annualNetTuitionCost?: number | null,
  fourYearNetTuitionCost?: number | null,
  annualEducationRelatedSpending?: number | null,
  shareOfStudentWhoGraduateIn4Years?: number | null,
  shareOfStudentWhoGraduateIn5Years?: number | null,
  shareOfStudentWhoGraduateIn6Years?: number | null,
  shareOfStudentWhoTransferOutIn6Years?: number | null,
  shareOfStudentWhoRemainIn6Years?: number | null,
  shareOfStudentWhoNoLongerEnrolledIn6Years?: number | null,
  absoluteIncreaseInLifetimeEarnings?: number | null,
  percentageIncreaseInLifetimeEarnings?: string | null,
  lifetimeReturnOnInvestmentROI?: number | null,
  ageAtWhichROITurnsPositive?: number | null,
  rankOfProgramByROI?: number | null,
  ROIIfStudentTakes5YearsToGraduate?: number | null,
  ROIIfStudentTakes6YearsToGraduate?: number | null,
  ROIIfStudentDropsBeforeGraduating?: number | null,
  ROIWeightedByInstitutionsCompletionOutcomes?: number | null,
  ROIBasedOnInstitutionsEducationRelatedSpending?: number | null,
  ROIBasedOnInstitutionsEducationRelatedSpending5years?: number | null,
  ROIBasedOnInstitutionsEducationRelatedSpending6Years?: number | null,
  ROIBasedOnInstitutionsEducationRelatedSpendingDrops?: number | null,
  ROIBasedOnInstitutionsEducationRelatedSpendingCompletionOutcomes?: number | null,
  estimatedEarnings23?: number | null,
  estimatedEarnings26?: number | null,
  estimatedEarnings29?: number | null,
  estimatedEarnings32?: number | null,
  estimatedEarnings35?: number | null,
  estimatedEarnings38?: number | null,
  estimatedEarnings41?: number | null,
  estimatedEarnings44?: number | null,
  estimatedEarnings47?: number | null,
  estimatedEarnings50?: number | null,
  estimatedEarnings53?: number | null,
  estimatedEarnings56?: number | null,
  estimatedEarnings59?: number | null,
  estimatedEarnings62?: number | null,
  estimatedCounterfactualEarnings19?: number | null,
  estimatedCounterfactualEarnings21?: number | null,
  estimatedCounterfactualEarnings23?: number | null,
  estimatedCounterfactualEarnings26?: number | null,
  estimatedCounterfactualEarnings29?: number | null,
  estimatedCounterfactualEarnings32?: number | null,
  estimatedCounterfactualEarnings35?: number | null,
  estimatedCounterfactualEarnings38?: number | null,
  estimatedCounterfactualEarnings41?: number | null,
  estimatedCounterfactualEarnings44?: number | null,
  estimatedCounterfactualEarnings47?: number | null,
  estimatedCounterfactualEarnings50?: number | null,
  estimatedCounterfactualEarnings53?: number | null,
  estimatedCounterfactualEarnings56?: number | null,
  estimatedCounterfactualEarnings59?: number | null,
  estimatedCounterfactualEarnings62?: number | null,
  resultsAvailableForAllSpecifications?: number | null,
  fourYearEducationRelatedSpending?: number | null,
  state?: string | null,
  createdAt: string,
  updatedAt: string,
  _version: number,
  _deleted?: boolean | null,
  _lastChangedAt: number,
};

export type UpdateROIInput = {
  id: string,
  uniqueId?: string | null,
  institutionName?: string | null,
  programName?: string | null,
  unitId?: number | null,
  stateFIPSCode?: number | null,
  programCIPCode?: number | null,
  programCategory?: string | null,
  control?: string | null,
  carnegieClassification2015?: string | null,
  admissionsRate?: number | null,
  credentialLevel?: number | null,
  credentialLevelDescription?: string | null,
  collegeScorecardCohortCount?: number | null,
  annualNetTuitionCost?: number | null,
  fourYearNetTuitionCost?: number | null,
  annualEducationRelatedSpending?: number | null,
  shareOfStudentWhoGraduateIn4Years?: number | null,
  shareOfStudentWhoGraduateIn5Years?: number | null,
  shareOfStudentWhoGraduateIn6Years?: number | null,
  shareOfStudentWhoTransferOutIn6Years?: number | null,
  shareOfStudentWhoRemainIn6Years?: number | null,
  shareOfStudentWhoNoLongerEnrolledIn6Years?: number | null,
  absoluteIncreaseInLifetimeEarnings?: number | null,
  percentageIncreaseInLifetimeEarnings?: string | null,
  lifetimeReturnOnInvestmentROI?: number | null,
  ageAtWhichROITurnsPositive?: number | null,
  rankOfProgramByROI?: number | null,
  ROIIfStudentTakes5YearsToGraduate?: number | null,
  ROIIfStudentTakes6YearsToGraduate?: number | null,
  ROIIfStudentDropsBeforeGraduating?: number | null,
  ROIWeightedByInstitutionsCompletionOutcomes?: number | null,
  ROIBasedOnInstitutionsEducationRelatedSpending?: number | null,
  ROIBasedOnInstitutionsEducationRelatedSpending5years?: number | null,
  ROIBasedOnInstitutionsEducationRelatedSpending6Years?: number | null,
  ROIBasedOnInstitutionsEducationRelatedSpendingDrops?: number | null,
  ROIBasedOnInstitutionsEducationRelatedSpendingCompletionOutcomes?: number | null,
  estimatedEarnings23?: number | null,
  estimatedEarnings26?: number | null,
  estimatedEarnings29?: number | null,
  estimatedEarnings32?: number | null,
  estimatedEarnings35?: number | null,
  estimatedEarnings38?: number | null,
  estimatedEarnings41?: number | null,
  estimatedEarnings44?: number | null,
  estimatedEarnings47?: number | null,
  estimatedEarnings50?: number | null,
  estimatedEarnings53?: number | null,
  estimatedEarnings56?: number | null,
  estimatedEarnings59?: number | null,
  estimatedEarnings62?: number | null,
  estimatedCounterfactualEarnings19?: number | null,
  estimatedCounterfactualEarnings21?: number | null,
  estimatedCounterfactualEarnings23?: number | null,
  estimatedCounterfactualEarnings26?: number | null,
  estimatedCounterfactualEarnings29?: number | null,
  estimatedCounterfactualEarnings32?: number | null,
  estimatedCounterfactualEarnings35?: number | null,
  estimatedCounterfactualEarnings38?: number | null,
  estimatedCounterfactualEarnings41?: number | null,
  estimatedCounterfactualEarnings44?: number | null,
  estimatedCounterfactualEarnings47?: number | null,
  estimatedCounterfactualEarnings50?: number | null,
  estimatedCounterfactualEarnings53?: number | null,
  estimatedCounterfactualEarnings56?: number | null,
  estimatedCounterfactualEarnings59?: number | null,
  estimatedCounterfactualEarnings62?: number | null,
  resultsAvailableForAllSpecifications?: number | null,
  fourYearEducationRelatedSpending?: number | null,
  state?: string | null,
  _version?: number | null,
};

export type DeleteROIInput = {
  id: string,
  _version?: number | null,
};

export type ModelUserInfoFilterInput = {
  id?: ModelIDInput | null,
  email?: ModelStringInput | null,
  dayPreferences?: ModelStringInput | null,
  timePreferences?: ModelStringInput | null,
  location?: ModelStringInput | null,
  modalityPreferences?: ModelStringInput | null,
  userType?: ModelStringInput | null,
  viewHistory?: ModelStringInput | null,
  searchHistory?: ModelStringInput | null,
  and?: Array< ModelUserInfoFilterInput | null > | null,
  or?: Array< ModelUserInfoFilterInput | null > | null,
  not?: ModelUserInfoFilterInput | null,
};

export type ModelIDInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  size?: ModelSizeInput | null,
};

export type ModelUserInfoConnection = {
  __typename: "ModelUserInfoConnection",
  items:  Array<UserInfo >,
  nextToken?: string | null,
  startedAt?: number | null,
};

export type ModelROIFilterInput = {
  id?: ModelIDInput | null,
  uniqueId?: ModelStringInput | null,
  institutionName?: ModelStringInput | null,
  programName?: ModelStringInput | null,
  unitId?: ModelIntInput | null,
  stateFIPSCode?: ModelIntInput | null,
  programCIPCode?: ModelIntInput | null,
  programCategory?: ModelStringInput | null,
  control?: ModelStringInput | null,
  carnegieClassification2015?: ModelStringInput | null,
  admissionsRate?: ModelIntInput | null,
  credentialLevel?: ModelIntInput | null,
  credentialLevelDescription?: ModelStringInput | null,
  collegeScorecardCohortCount?: ModelIntInput | null,
  annualNetTuitionCost?: ModelIntInput | null,
  fourYearNetTuitionCost?: ModelIntInput | null,
  annualEducationRelatedSpending?: ModelIntInput | null,
  shareOfStudentWhoGraduateIn4Years?: ModelFloatInput | null,
  shareOfStudentWhoGraduateIn5Years?: ModelFloatInput | null,
  shareOfStudentWhoGraduateIn6Years?: ModelFloatInput | null,
  shareOfStudentWhoTransferOutIn6Years?: ModelFloatInput | null,
  shareOfStudentWhoRemainIn6Years?: ModelFloatInput | null,
  shareOfStudentWhoNoLongerEnrolledIn6Years?: ModelFloatInput | null,
  absoluteIncreaseInLifetimeEarnings?: ModelIntInput | null,
  percentageIncreaseInLifetimeEarnings?: ModelStringInput | null,
  lifetimeReturnOnInvestmentROI?: ModelIntInput | null,
  ageAtWhichROITurnsPositive?: ModelIntInput | null,
  rankOfProgramByROI?: ModelIntInput | null,
  ROIIfStudentTakes5YearsToGraduate?: ModelIntInput | null,
  ROIIfStudentTakes6YearsToGraduate?: ModelIntInput | null,
  ROIIfStudentDropsBeforeGraduating?: ModelIntInput | null,
  ROIWeightedByInstitutionsCompletionOutcomes?: ModelIntInput | null,
  ROIBasedOnInstitutionsEducationRelatedSpending?: ModelIntInput | null,
  ROIBasedOnInstitutionsEducationRelatedSpending5years?: ModelIntInput | null,
  ROIBasedOnInstitutionsEducationRelatedSpending6Years?: ModelIntInput | null,
  ROIBasedOnInstitutionsEducationRelatedSpendingDrops?: ModelIntInput | null,
  ROIBasedOnInstitutionsEducationRelatedSpendingCompletionOutcomes?: ModelIntInput | null,
  estimatedEarnings23?: ModelIntInput | null,
  estimatedEarnings26?: ModelIntInput | null,
  estimatedEarnings29?: ModelIntInput | null,
  estimatedEarnings32?: ModelIntInput | null,
  estimatedEarnings35?: ModelIntInput | null,
  estimatedEarnings38?: ModelIntInput | null,
  estimatedEarnings41?: ModelIntInput | null,
  estimatedEarnings44?: ModelIntInput | null,
  estimatedEarnings47?: ModelIntInput | null,
  estimatedEarnings50?: ModelIntInput | null,
  estimatedEarnings53?: ModelIntInput | null,
  estimatedEarnings56?: ModelIntInput | null,
  estimatedEarnings59?: ModelIntInput | null,
  estimatedEarnings62?: ModelIntInput | null,
  estimatedCounterfactualEarnings19?: ModelIntInput | null,
  estimatedCounterfactualEarnings21?: ModelIntInput | null,
  estimatedCounterfactualEarnings23?: ModelIntInput | null,
  estimatedCounterfactualEarnings26?: ModelIntInput | null,
  estimatedCounterfactualEarnings29?: ModelIntInput | null,
  estimatedCounterfactualEarnings32?: ModelIntInput | null,
  estimatedCounterfactualEarnings35?: ModelIntInput | null,
  estimatedCounterfactualEarnings38?: ModelIntInput | null,
  estimatedCounterfactualEarnings41?: ModelIntInput | null,
  estimatedCounterfactualEarnings44?: ModelIntInput | null,
  estimatedCounterfactualEarnings47?: ModelIntInput | null,
  estimatedCounterfactualEarnings50?: ModelIntInput | null,
  estimatedCounterfactualEarnings53?: ModelIntInput | null,
  estimatedCounterfactualEarnings56?: ModelIntInput | null,
  estimatedCounterfactualEarnings59?: ModelIntInput | null,
  estimatedCounterfactualEarnings62?: ModelIntInput | null,
  resultsAvailableForAllSpecifications?: ModelIntInput | null,
  fourYearEducationRelatedSpending?: ModelIntInput | null,
  state?: ModelStringInput | null,
  and?: Array< ModelROIFilterInput | null > | null,
  or?: Array< ModelROIFilterInput | null > | null,
  not?: ModelROIFilterInput | null,
};

export type ModelROIConnection = {
  __typename: "ModelROIConnection",
  items:  Array<ROI >,
  nextToken?: string | null,
  startedAt?: number | null,
};

export type CreateUserInfoMutationVariables = {
  input: CreateUserInfoInput,
  condition?: ModelUserInfoConditionInput | null,
};

export type CreateUserInfoMutation = {
  createUserInfo?:  {
    __typename: "UserInfo",
    id: string,
    email?: string | null,
    dayPreferences?: string | null,
    timePreferences?: string | null,
    location?: string | null,
    modalityPreferences?: string | null,
    userType?: string | null,
    viewHistory?: string | null,
    searchHistory?: string | null,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
    owner?: string | null,
  } | null,
};

export type UpdateUserInfoMutationVariables = {
  input: UpdateUserInfoInput,
  condition?: ModelUserInfoConditionInput | null,
};

export type UpdateUserInfoMutation = {
  updateUserInfo?:  {
    __typename: "UserInfo",
    id: string,
    email?: string | null,
    dayPreferences?: string | null,
    timePreferences?: string | null,
    location?: string | null,
    modalityPreferences?: string | null,
    userType?: string | null,
    viewHistory?: string | null,
    searchHistory?: string | null,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
    owner?: string | null,
  } | null,
};

export type DeleteUserInfoMutationVariables = {
  input: DeleteUserInfoInput,
  condition?: ModelUserInfoConditionInput | null,
};

export type DeleteUserInfoMutation = {
  deleteUserInfo?:  {
    __typename: "UserInfo",
    id: string,
    email?: string | null,
    dayPreferences?: string | null,
    timePreferences?: string | null,
    location?: string | null,
    modalityPreferences?: string | null,
    userType?: string | null,
    viewHistory?: string | null,
    searchHistory?: string | null,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
    owner?: string | null,
  } | null,
};

export type CreateROIMutationVariables = {
  input: CreateROIInput,
  condition?: ModelROIConditionInput | null,
};

export type CreateROIMutation = {
  createROI?:  {
    __typename: "ROI",
    id: string,
    uniqueId?: string | null,
    institutionName?: string | null,
    programName?: string | null,
    unitId?: number | null,
    stateFIPSCode?: number | null,
    programCIPCode?: number | null,
    programCategory?: string | null,
    control?: string | null,
    carnegieClassification2015?: string | null,
    admissionsRate?: number | null,
    credentialLevel?: number | null,
    credentialLevelDescription?: string | null,
    collegeScorecardCohortCount?: number | null,
    annualNetTuitionCost?: number | null,
    fourYearNetTuitionCost?: number | null,
    annualEducationRelatedSpending?: number | null,
    shareOfStudentWhoGraduateIn4Years?: number | null,
    shareOfStudentWhoGraduateIn5Years?: number | null,
    shareOfStudentWhoGraduateIn6Years?: number | null,
    shareOfStudentWhoTransferOutIn6Years?: number | null,
    shareOfStudentWhoRemainIn6Years?: number | null,
    shareOfStudentWhoNoLongerEnrolledIn6Years?: number | null,
    absoluteIncreaseInLifetimeEarnings?: number | null,
    percentageIncreaseInLifetimeEarnings?: string | null,
    lifetimeReturnOnInvestmentROI?: number | null,
    ageAtWhichROITurnsPositive?: number | null,
    rankOfProgramByROI?: number | null,
    ROIIfStudentTakes5YearsToGraduate?: number | null,
    ROIIfStudentTakes6YearsToGraduate?: number | null,
    ROIIfStudentDropsBeforeGraduating?: number | null,
    ROIWeightedByInstitutionsCompletionOutcomes?: number | null,
    ROIBasedOnInstitutionsEducationRelatedSpending?: number | null,
    ROIBasedOnInstitutionsEducationRelatedSpending5years?: number | null,
    ROIBasedOnInstitutionsEducationRelatedSpending6Years?: number | null,
    ROIBasedOnInstitutionsEducationRelatedSpendingDrops?: number | null,
    ROIBasedOnInstitutionsEducationRelatedSpendingCompletionOutcomes?: number | null,
    estimatedEarnings23?: number | null,
    estimatedEarnings26?: number | null,
    estimatedEarnings29?: number | null,
    estimatedEarnings32?: number | null,
    estimatedEarnings35?: number | null,
    estimatedEarnings38?: number | null,
    estimatedEarnings41?: number | null,
    estimatedEarnings44?: number | null,
    estimatedEarnings47?: number | null,
    estimatedEarnings50?: number | null,
    estimatedEarnings53?: number | null,
    estimatedEarnings56?: number | null,
    estimatedEarnings59?: number | null,
    estimatedEarnings62?: number | null,
    estimatedCounterfactualEarnings19?: number | null,
    estimatedCounterfactualEarnings21?: number | null,
    estimatedCounterfactualEarnings23?: number | null,
    estimatedCounterfactualEarnings26?: number | null,
    estimatedCounterfactualEarnings29?: number | null,
    estimatedCounterfactualEarnings32?: number | null,
    estimatedCounterfactualEarnings35?: number | null,
    estimatedCounterfactualEarnings38?: number | null,
    estimatedCounterfactualEarnings41?: number | null,
    estimatedCounterfactualEarnings44?: number | null,
    estimatedCounterfactualEarnings47?: number | null,
    estimatedCounterfactualEarnings50?: number | null,
    estimatedCounterfactualEarnings53?: number | null,
    estimatedCounterfactualEarnings56?: number | null,
    estimatedCounterfactualEarnings59?: number | null,
    estimatedCounterfactualEarnings62?: number | null,
    resultsAvailableForAllSpecifications?: number | null,
    fourYearEducationRelatedSpending?: number | null,
    state?: string | null,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type UpdateROIMutationVariables = {
  input: UpdateROIInput,
  condition?: ModelROIConditionInput | null,
};

export type UpdateROIMutation = {
  updateROI?:  {
    __typename: "ROI",
    id: string,
    uniqueId?: string | null,
    institutionName?: string | null,
    programName?: string | null,
    unitId?: number | null,
    stateFIPSCode?: number | null,
    programCIPCode?: number | null,
    programCategory?: string | null,
    control?: string | null,
    carnegieClassification2015?: string | null,
    admissionsRate?: number | null,
    credentialLevel?: number | null,
    credentialLevelDescription?: string | null,
    collegeScorecardCohortCount?: number | null,
    annualNetTuitionCost?: number | null,
    fourYearNetTuitionCost?: number | null,
    annualEducationRelatedSpending?: number | null,
    shareOfStudentWhoGraduateIn4Years?: number | null,
    shareOfStudentWhoGraduateIn5Years?: number | null,
    shareOfStudentWhoGraduateIn6Years?: number | null,
    shareOfStudentWhoTransferOutIn6Years?: number | null,
    shareOfStudentWhoRemainIn6Years?: number | null,
    shareOfStudentWhoNoLongerEnrolledIn6Years?: number | null,
    absoluteIncreaseInLifetimeEarnings?: number | null,
    percentageIncreaseInLifetimeEarnings?: string | null,
    lifetimeReturnOnInvestmentROI?: number | null,
    ageAtWhichROITurnsPositive?: number | null,
    rankOfProgramByROI?: number | null,
    ROIIfStudentTakes5YearsToGraduate?: number | null,
    ROIIfStudentTakes6YearsToGraduate?: number | null,
    ROIIfStudentDropsBeforeGraduating?: number | null,
    ROIWeightedByInstitutionsCompletionOutcomes?: number | null,
    ROIBasedOnInstitutionsEducationRelatedSpending?: number | null,
    ROIBasedOnInstitutionsEducationRelatedSpending5years?: number | null,
    ROIBasedOnInstitutionsEducationRelatedSpending6Years?: number | null,
    ROIBasedOnInstitutionsEducationRelatedSpendingDrops?: number | null,
    ROIBasedOnInstitutionsEducationRelatedSpendingCompletionOutcomes?: number | null,
    estimatedEarnings23?: number | null,
    estimatedEarnings26?: number | null,
    estimatedEarnings29?: number | null,
    estimatedEarnings32?: number | null,
    estimatedEarnings35?: number | null,
    estimatedEarnings38?: number | null,
    estimatedEarnings41?: number | null,
    estimatedEarnings44?: number | null,
    estimatedEarnings47?: number | null,
    estimatedEarnings50?: number | null,
    estimatedEarnings53?: number | null,
    estimatedEarnings56?: number | null,
    estimatedEarnings59?: number | null,
    estimatedEarnings62?: number | null,
    estimatedCounterfactualEarnings19?: number | null,
    estimatedCounterfactualEarnings21?: number | null,
    estimatedCounterfactualEarnings23?: number | null,
    estimatedCounterfactualEarnings26?: number | null,
    estimatedCounterfactualEarnings29?: number | null,
    estimatedCounterfactualEarnings32?: number | null,
    estimatedCounterfactualEarnings35?: number | null,
    estimatedCounterfactualEarnings38?: number | null,
    estimatedCounterfactualEarnings41?: number | null,
    estimatedCounterfactualEarnings44?: number | null,
    estimatedCounterfactualEarnings47?: number | null,
    estimatedCounterfactualEarnings50?: number | null,
    estimatedCounterfactualEarnings53?: number | null,
    estimatedCounterfactualEarnings56?: number | null,
    estimatedCounterfactualEarnings59?: number | null,
    estimatedCounterfactualEarnings62?: number | null,
    resultsAvailableForAllSpecifications?: number | null,
    fourYearEducationRelatedSpending?: number | null,
    state?: string | null,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type DeleteROIMutationVariables = {
  input: DeleteROIInput,
  condition?: ModelROIConditionInput | null,
};

export type DeleteROIMutation = {
  deleteROI?:  {
    __typename: "ROI",
    id: string,
    uniqueId?: string | null,
    institutionName?: string | null,
    programName?: string | null,
    unitId?: number | null,
    stateFIPSCode?: number | null,
    programCIPCode?: number | null,
    programCategory?: string | null,
    control?: string | null,
    carnegieClassification2015?: string | null,
    admissionsRate?: number | null,
    credentialLevel?: number | null,
    credentialLevelDescription?: string | null,
    collegeScorecardCohortCount?: number | null,
    annualNetTuitionCost?: number | null,
    fourYearNetTuitionCost?: number | null,
    annualEducationRelatedSpending?: number | null,
    shareOfStudentWhoGraduateIn4Years?: number | null,
    shareOfStudentWhoGraduateIn5Years?: number | null,
    shareOfStudentWhoGraduateIn6Years?: number | null,
    shareOfStudentWhoTransferOutIn6Years?: number | null,
    shareOfStudentWhoRemainIn6Years?: number | null,
    shareOfStudentWhoNoLongerEnrolledIn6Years?: number | null,
    absoluteIncreaseInLifetimeEarnings?: number | null,
    percentageIncreaseInLifetimeEarnings?: string | null,
    lifetimeReturnOnInvestmentROI?: number | null,
    ageAtWhichROITurnsPositive?: number | null,
    rankOfProgramByROI?: number | null,
    ROIIfStudentTakes5YearsToGraduate?: number | null,
    ROIIfStudentTakes6YearsToGraduate?: number | null,
    ROIIfStudentDropsBeforeGraduating?: number | null,
    ROIWeightedByInstitutionsCompletionOutcomes?: number | null,
    ROIBasedOnInstitutionsEducationRelatedSpending?: number | null,
    ROIBasedOnInstitutionsEducationRelatedSpending5years?: number | null,
    ROIBasedOnInstitutionsEducationRelatedSpending6Years?: number | null,
    ROIBasedOnInstitutionsEducationRelatedSpendingDrops?: number | null,
    ROIBasedOnInstitutionsEducationRelatedSpendingCompletionOutcomes?: number | null,
    estimatedEarnings23?: number | null,
    estimatedEarnings26?: number | null,
    estimatedEarnings29?: number | null,
    estimatedEarnings32?: number | null,
    estimatedEarnings35?: number | null,
    estimatedEarnings38?: number | null,
    estimatedEarnings41?: number | null,
    estimatedEarnings44?: number | null,
    estimatedEarnings47?: number | null,
    estimatedEarnings50?: number | null,
    estimatedEarnings53?: number | null,
    estimatedEarnings56?: number | null,
    estimatedEarnings59?: number | null,
    estimatedEarnings62?: number | null,
    estimatedCounterfactualEarnings19?: number | null,
    estimatedCounterfactualEarnings21?: number | null,
    estimatedCounterfactualEarnings23?: number | null,
    estimatedCounterfactualEarnings26?: number | null,
    estimatedCounterfactualEarnings29?: number | null,
    estimatedCounterfactualEarnings32?: number | null,
    estimatedCounterfactualEarnings35?: number | null,
    estimatedCounterfactualEarnings38?: number | null,
    estimatedCounterfactualEarnings41?: number | null,
    estimatedCounterfactualEarnings44?: number | null,
    estimatedCounterfactualEarnings47?: number | null,
    estimatedCounterfactualEarnings50?: number | null,
    estimatedCounterfactualEarnings53?: number | null,
    estimatedCounterfactualEarnings56?: number | null,
    estimatedCounterfactualEarnings59?: number | null,
    estimatedCounterfactualEarnings62?: number | null,
    resultsAvailableForAllSpecifications?: number | null,
    fourYearEducationRelatedSpending?: number | null,
    state?: string | null,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type GetUserInfoQueryVariables = {
  id: string,
};

export type GetUserInfoQuery = {
  getUserInfo?:  {
    __typename: "UserInfo",
    id: string,
    email?: string | null,
    dayPreferences?: string | null,
    timePreferences?: string | null,
    location?: string | null,
    modalityPreferences?: string | null,
    userType?: string | null,
    viewHistory?: string | null,
    searchHistory?: string | null,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
    owner?: string | null,
  } | null,
};

export type ListUserInfosQueryVariables = {
  filter?: ModelUserInfoFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListUserInfosQuery = {
  listUserInfos?:  {
    __typename: "ModelUserInfoConnection",
    items:  Array< {
      __typename: "UserInfo",
      id: string,
      email?: string | null,
      dayPreferences?: string | null,
      timePreferences?: string | null,
      location?: string | null,
      modalityPreferences?: string | null,
      userType?: string | null,
      viewHistory?: string | null,
      searchHistory?: string | null,
      createdAt: string,
      updatedAt: string,
      _version: number,
      _deleted?: boolean | null,
      _lastChangedAt: number,
      owner?: string | null,
    } >,
    nextToken?: string | null,
    startedAt?: number | null,
  } | null,
};

export type SyncUserInfosQueryVariables = {
  filter?: ModelUserInfoFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
  lastSync?: number | null,
};

export type SyncUserInfosQuery = {
  syncUserInfos?:  {
    __typename: "ModelUserInfoConnection",
    items:  Array< {
      __typename: "UserInfo",
      id: string,
      email?: string | null,
      dayPreferences?: string | null,
      timePreferences?: string | null,
      location?: string | null,
      modalityPreferences?: string | null,
      userType?: string | null,
      viewHistory?: string | null,
      searchHistory?: string | null,
      createdAt: string,
      updatedAt: string,
      _version: number,
      _deleted?: boolean | null,
      _lastChangedAt: number,
      owner?: string | null,
    } >,
    nextToken?: string | null,
    startedAt?: number | null,
  } | null,
};

export type GetROIQueryVariables = {
  id: string,
};

export type GetROIQuery = {
  getROI?:  {
    __typename: "ROI",
    id: string,
    uniqueId?: string | null,
    institutionName?: string | null,
    programName?: string | null,
    unitId?: number | null,
    stateFIPSCode?: number | null,
    programCIPCode?: number | null,
    programCategory?: string | null,
    control?: string | null,
    carnegieClassification2015?: string | null,
    admissionsRate?: number | null,
    credentialLevel?: number | null,
    credentialLevelDescription?: string | null,
    collegeScorecardCohortCount?: number | null,
    annualNetTuitionCost?: number | null,
    fourYearNetTuitionCost?: number | null,
    annualEducationRelatedSpending?: number | null,
    shareOfStudentWhoGraduateIn4Years?: number | null,
    shareOfStudentWhoGraduateIn5Years?: number | null,
    shareOfStudentWhoGraduateIn6Years?: number | null,
    shareOfStudentWhoTransferOutIn6Years?: number | null,
    shareOfStudentWhoRemainIn6Years?: number | null,
    shareOfStudentWhoNoLongerEnrolledIn6Years?: number | null,
    absoluteIncreaseInLifetimeEarnings?: number | null,
    percentageIncreaseInLifetimeEarnings?: string | null,
    lifetimeReturnOnInvestmentROI?: number | null,
    ageAtWhichROITurnsPositive?: number | null,
    rankOfProgramByROI?: number | null,
    ROIIfStudentTakes5YearsToGraduate?: number | null,
    ROIIfStudentTakes6YearsToGraduate?: number | null,
    ROIIfStudentDropsBeforeGraduating?: number | null,
    ROIWeightedByInstitutionsCompletionOutcomes?: number | null,
    ROIBasedOnInstitutionsEducationRelatedSpending?: number | null,
    ROIBasedOnInstitutionsEducationRelatedSpending5years?: number | null,
    ROIBasedOnInstitutionsEducationRelatedSpending6Years?: number | null,
    ROIBasedOnInstitutionsEducationRelatedSpendingDrops?: number | null,
    ROIBasedOnInstitutionsEducationRelatedSpendingCompletionOutcomes?: number | null,
    estimatedEarnings23?: number | null,
    estimatedEarnings26?: number | null,
    estimatedEarnings29?: number | null,
    estimatedEarnings32?: number | null,
    estimatedEarnings35?: number | null,
    estimatedEarnings38?: number | null,
    estimatedEarnings41?: number | null,
    estimatedEarnings44?: number | null,
    estimatedEarnings47?: number | null,
    estimatedEarnings50?: number | null,
    estimatedEarnings53?: number | null,
    estimatedEarnings56?: number | null,
    estimatedEarnings59?: number | null,
    estimatedEarnings62?: number | null,
    estimatedCounterfactualEarnings19?: number | null,
    estimatedCounterfactualEarnings21?: number | null,
    estimatedCounterfactualEarnings23?: number | null,
    estimatedCounterfactualEarnings26?: number | null,
    estimatedCounterfactualEarnings29?: number | null,
    estimatedCounterfactualEarnings32?: number | null,
    estimatedCounterfactualEarnings35?: number | null,
    estimatedCounterfactualEarnings38?: number | null,
    estimatedCounterfactualEarnings41?: number | null,
    estimatedCounterfactualEarnings44?: number | null,
    estimatedCounterfactualEarnings47?: number | null,
    estimatedCounterfactualEarnings50?: number | null,
    estimatedCounterfactualEarnings53?: number | null,
    estimatedCounterfactualEarnings56?: number | null,
    estimatedCounterfactualEarnings59?: number | null,
    estimatedCounterfactualEarnings62?: number | null,
    resultsAvailableForAllSpecifications?: number | null,
    fourYearEducationRelatedSpending?: number | null,
    state?: string | null,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type ListROISQueryVariables = {
  filter?: ModelROIFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListROISQuery = {
  listROIS?:  {
    __typename: "ModelROIConnection",
    items:  Array< {
      __typename: "ROI",
      id: string,
      uniqueId?: string | null,
      institutionName?: string | null,
      programName?: string | null,
      unitId?: number | null,
      stateFIPSCode?: number | null,
      programCIPCode?: number | null,
      programCategory?: string | null,
      control?: string | null,
      carnegieClassification2015?: string | null,
      admissionsRate?: number | null,
      credentialLevel?: number | null,
      credentialLevelDescription?: string | null,
      collegeScorecardCohortCount?: number | null,
      annualNetTuitionCost?: number | null,
      fourYearNetTuitionCost?: number | null,
      annualEducationRelatedSpending?: number | null,
      shareOfStudentWhoGraduateIn4Years?: number | null,
      shareOfStudentWhoGraduateIn5Years?: number | null,
      shareOfStudentWhoGraduateIn6Years?: number | null,
      shareOfStudentWhoTransferOutIn6Years?: number | null,
      shareOfStudentWhoRemainIn6Years?: number | null,
      shareOfStudentWhoNoLongerEnrolledIn6Years?: number | null,
      absoluteIncreaseInLifetimeEarnings?: number | null,
      percentageIncreaseInLifetimeEarnings?: string | null,
      lifetimeReturnOnInvestmentROI?: number | null,
      ageAtWhichROITurnsPositive?: number | null,
      rankOfProgramByROI?: number | null,
      ROIIfStudentTakes5YearsToGraduate?: number | null,
      ROIIfStudentTakes6YearsToGraduate?: number | null,
      ROIIfStudentDropsBeforeGraduating?: number | null,
      ROIWeightedByInstitutionsCompletionOutcomes?: number | null,
      ROIBasedOnInstitutionsEducationRelatedSpending?: number | null,
      ROIBasedOnInstitutionsEducationRelatedSpending5years?: number | null,
      ROIBasedOnInstitutionsEducationRelatedSpending6Years?: number | null,
      ROIBasedOnInstitutionsEducationRelatedSpendingDrops?: number | null,
      ROIBasedOnInstitutionsEducationRelatedSpendingCompletionOutcomes?: number | null,
      estimatedEarnings23?: number | null,
      estimatedEarnings26?: number | null,
      estimatedEarnings29?: number | null,
      estimatedEarnings32?: number | null,
      estimatedEarnings35?: number | null,
      estimatedEarnings38?: number | null,
      estimatedEarnings41?: number | null,
      estimatedEarnings44?: number | null,
      estimatedEarnings47?: number | null,
      estimatedEarnings50?: number | null,
      estimatedEarnings53?: number | null,
      estimatedEarnings56?: number | null,
      estimatedEarnings59?: number | null,
      estimatedEarnings62?: number | null,
      estimatedCounterfactualEarnings19?: number | null,
      estimatedCounterfactualEarnings21?: number | null,
      estimatedCounterfactualEarnings23?: number | null,
      estimatedCounterfactualEarnings26?: number | null,
      estimatedCounterfactualEarnings29?: number | null,
      estimatedCounterfactualEarnings32?: number | null,
      estimatedCounterfactualEarnings35?: number | null,
      estimatedCounterfactualEarnings38?: number | null,
      estimatedCounterfactualEarnings41?: number | null,
      estimatedCounterfactualEarnings44?: number | null,
      estimatedCounterfactualEarnings47?: number | null,
      estimatedCounterfactualEarnings50?: number | null,
      estimatedCounterfactualEarnings53?: number | null,
      estimatedCounterfactualEarnings56?: number | null,
      estimatedCounterfactualEarnings59?: number | null,
      estimatedCounterfactualEarnings62?: number | null,
      resultsAvailableForAllSpecifications?: number | null,
      fourYearEducationRelatedSpending?: number | null,
      state?: string | null,
      createdAt: string,
      updatedAt: string,
      _version: number,
      _deleted?: boolean | null,
      _lastChangedAt: number,
    } >,
    nextToken?: string | null,
    startedAt?: number | null,
  } | null,
};

export type SyncROISQueryVariables = {
  filter?: ModelROIFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
  lastSync?: number | null,
};

export type SyncROISQuery = {
  syncROIS?:  {
    __typename: "ModelROIConnection",
    items:  Array< {
      __typename: "ROI",
      id: string,
      uniqueId?: string | null,
      institutionName?: string | null,
      programName?: string | null,
      unitId?: number | null,
      stateFIPSCode?: number | null,
      programCIPCode?: number | null,
      programCategory?: string | null,
      control?: string | null,
      carnegieClassification2015?: string | null,
      admissionsRate?: number | null,
      credentialLevel?: number | null,
      credentialLevelDescription?: string | null,
      collegeScorecardCohortCount?: number | null,
      annualNetTuitionCost?: number | null,
      fourYearNetTuitionCost?: number | null,
      annualEducationRelatedSpending?: number | null,
      shareOfStudentWhoGraduateIn4Years?: number | null,
      shareOfStudentWhoGraduateIn5Years?: number | null,
      shareOfStudentWhoGraduateIn6Years?: number | null,
      shareOfStudentWhoTransferOutIn6Years?: number | null,
      shareOfStudentWhoRemainIn6Years?: number | null,
      shareOfStudentWhoNoLongerEnrolledIn6Years?: number | null,
      absoluteIncreaseInLifetimeEarnings?: number | null,
      percentageIncreaseInLifetimeEarnings?: string | null,
      lifetimeReturnOnInvestmentROI?: number | null,
      ageAtWhichROITurnsPositive?: number | null,
      rankOfProgramByROI?: number | null,
      ROIIfStudentTakes5YearsToGraduate?: number | null,
      ROIIfStudentTakes6YearsToGraduate?: number | null,
      ROIIfStudentDropsBeforeGraduating?: number | null,
      ROIWeightedByInstitutionsCompletionOutcomes?: number | null,
      ROIBasedOnInstitutionsEducationRelatedSpending?: number | null,
      ROIBasedOnInstitutionsEducationRelatedSpending5years?: number | null,
      ROIBasedOnInstitutionsEducationRelatedSpending6Years?: number | null,
      ROIBasedOnInstitutionsEducationRelatedSpendingDrops?: number | null,
      ROIBasedOnInstitutionsEducationRelatedSpendingCompletionOutcomes?: number | null,
      estimatedEarnings23?: number | null,
      estimatedEarnings26?: number | null,
      estimatedEarnings29?: number | null,
      estimatedEarnings32?: number | null,
      estimatedEarnings35?: number | null,
      estimatedEarnings38?: number | null,
      estimatedEarnings41?: number | null,
      estimatedEarnings44?: number | null,
      estimatedEarnings47?: number | null,
      estimatedEarnings50?: number | null,
      estimatedEarnings53?: number | null,
      estimatedEarnings56?: number | null,
      estimatedEarnings59?: number | null,
      estimatedEarnings62?: number | null,
      estimatedCounterfactualEarnings19?: number | null,
      estimatedCounterfactualEarnings21?: number | null,
      estimatedCounterfactualEarnings23?: number | null,
      estimatedCounterfactualEarnings26?: number | null,
      estimatedCounterfactualEarnings29?: number | null,
      estimatedCounterfactualEarnings32?: number | null,
      estimatedCounterfactualEarnings35?: number | null,
      estimatedCounterfactualEarnings38?: number | null,
      estimatedCounterfactualEarnings41?: number | null,
      estimatedCounterfactualEarnings44?: number | null,
      estimatedCounterfactualEarnings47?: number | null,
      estimatedCounterfactualEarnings50?: number | null,
      estimatedCounterfactualEarnings53?: number | null,
      estimatedCounterfactualEarnings56?: number | null,
      estimatedCounterfactualEarnings59?: number | null,
      estimatedCounterfactualEarnings62?: number | null,
      resultsAvailableForAllSpecifications?: number | null,
      fourYearEducationRelatedSpending?: number | null,
      state?: string | null,
      createdAt: string,
      updatedAt: string,
      _version: number,
      _deleted?: boolean | null,
      _lastChangedAt: number,
    } >,
    nextToken?: string | null,
    startedAt?: number | null,
  } | null,
};

export type OnCreateUserInfoSubscriptionVariables = {
  owner?: string | null,
};

export type OnCreateUserInfoSubscription = {
  onCreateUserInfo?:  {
    __typename: "UserInfo",
    id: string,
    email?: string | null,
    dayPreferences?: string | null,
    timePreferences?: string | null,
    location?: string | null,
    modalityPreferences?: string | null,
    userType?: string | null,
    viewHistory?: string | null,
    searchHistory?: string | null,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
    owner?: string | null,
  } | null,
};

export type OnUpdateUserInfoSubscriptionVariables = {
  owner?: string | null,
};

export type OnUpdateUserInfoSubscription = {
  onUpdateUserInfo?:  {
    __typename: "UserInfo",
    id: string,
    email?: string | null,
    dayPreferences?: string | null,
    timePreferences?: string | null,
    location?: string | null,
    modalityPreferences?: string | null,
    userType?: string | null,
    viewHistory?: string | null,
    searchHistory?: string | null,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
    owner?: string | null,
  } | null,
};

export type OnDeleteUserInfoSubscriptionVariables = {
  owner?: string | null,
};

export type OnDeleteUserInfoSubscription = {
  onDeleteUserInfo?:  {
    __typename: "UserInfo",
    id: string,
    email?: string | null,
    dayPreferences?: string | null,
    timePreferences?: string | null,
    location?: string | null,
    modalityPreferences?: string | null,
    userType?: string | null,
    viewHistory?: string | null,
    searchHistory?: string | null,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
    owner?: string | null,
  } | null,
};

export type OnCreateROISubscription = {
  onCreateROI?:  {
    __typename: "ROI",
    id: string,
    uniqueId?: string | null,
    institutionName?: string | null,
    programName?: string | null,
    unitId?: number | null,
    stateFIPSCode?: number | null,
    programCIPCode?: number | null,
    programCategory?: string | null,
    control?: string | null,
    carnegieClassification2015?: string | null,
    admissionsRate?: number | null,
    credentialLevel?: number | null,
    credentialLevelDescription?: string | null,
    collegeScorecardCohortCount?: number | null,
    annualNetTuitionCost?: number | null,
    fourYearNetTuitionCost?: number | null,
    annualEducationRelatedSpending?: number | null,
    shareOfStudentWhoGraduateIn4Years?: number | null,
    shareOfStudentWhoGraduateIn5Years?: number | null,
    shareOfStudentWhoGraduateIn6Years?: number | null,
    shareOfStudentWhoTransferOutIn6Years?: number | null,
    shareOfStudentWhoRemainIn6Years?: number | null,
    shareOfStudentWhoNoLongerEnrolledIn6Years?: number | null,
    absoluteIncreaseInLifetimeEarnings?: number | null,
    percentageIncreaseInLifetimeEarnings?: string | null,
    lifetimeReturnOnInvestmentROI?: number | null,
    ageAtWhichROITurnsPositive?: number | null,
    rankOfProgramByROI?: number | null,
    ROIIfStudentTakes5YearsToGraduate?: number | null,
    ROIIfStudentTakes6YearsToGraduate?: number | null,
    ROIIfStudentDropsBeforeGraduating?: number | null,
    ROIWeightedByInstitutionsCompletionOutcomes?: number | null,
    ROIBasedOnInstitutionsEducationRelatedSpending?: number | null,
    ROIBasedOnInstitutionsEducationRelatedSpending5years?: number | null,
    ROIBasedOnInstitutionsEducationRelatedSpending6Years?: number | null,
    ROIBasedOnInstitutionsEducationRelatedSpendingDrops?: number | null,
    ROIBasedOnInstitutionsEducationRelatedSpendingCompletionOutcomes?: number | null,
    estimatedEarnings23?: number | null,
    estimatedEarnings26?: number | null,
    estimatedEarnings29?: number | null,
    estimatedEarnings32?: number | null,
    estimatedEarnings35?: number | null,
    estimatedEarnings38?: number | null,
    estimatedEarnings41?: number | null,
    estimatedEarnings44?: number | null,
    estimatedEarnings47?: number | null,
    estimatedEarnings50?: number | null,
    estimatedEarnings53?: number | null,
    estimatedEarnings56?: number | null,
    estimatedEarnings59?: number | null,
    estimatedEarnings62?: number | null,
    estimatedCounterfactualEarnings19?: number | null,
    estimatedCounterfactualEarnings21?: number | null,
    estimatedCounterfactualEarnings23?: number | null,
    estimatedCounterfactualEarnings26?: number | null,
    estimatedCounterfactualEarnings29?: number | null,
    estimatedCounterfactualEarnings32?: number | null,
    estimatedCounterfactualEarnings35?: number | null,
    estimatedCounterfactualEarnings38?: number | null,
    estimatedCounterfactualEarnings41?: number | null,
    estimatedCounterfactualEarnings44?: number | null,
    estimatedCounterfactualEarnings47?: number | null,
    estimatedCounterfactualEarnings50?: number | null,
    estimatedCounterfactualEarnings53?: number | null,
    estimatedCounterfactualEarnings56?: number | null,
    estimatedCounterfactualEarnings59?: number | null,
    estimatedCounterfactualEarnings62?: number | null,
    resultsAvailableForAllSpecifications?: number | null,
    fourYearEducationRelatedSpending?: number | null,
    state?: string | null,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type OnUpdateROISubscription = {
  onUpdateROI?:  {
    __typename: "ROI",
    id: string,
    uniqueId?: string | null,
    institutionName?: string | null,
    programName?: string | null,
    unitId?: number | null,
    stateFIPSCode?: number | null,
    programCIPCode?: number | null,
    programCategory?: string | null,
    control?: string | null,
    carnegieClassification2015?: string | null,
    admissionsRate?: number | null,
    credentialLevel?: number | null,
    credentialLevelDescription?: string | null,
    collegeScorecardCohortCount?: number | null,
    annualNetTuitionCost?: number | null,
    fourYearNetTuitionCost?: number | null,
    annualEducationRelatedSpending?: number | null,
    shareOfStudentWhoGraduateIn4Years?: number | null,
    shareOfStudentWhoGraduateIn5Years?: number | null,
    shareOfStudentWhoGraduateIn6Years?: number | null,
    shareOfStudentWhoTransferOutIn6Years?: number | null,
    shareOfStudentWhoRemainIn6Years?: number | null,
    shareOfStudentWhoNoLongerEnrolledIn6Years?: number | null,
    absoluteIncreaseInLifetimeEarnings?: number | null,
    percentageIncreaseInLifetimeEarnings?: string | null,
    lifetimeReturnOnInvestmentROI?: number | null,
    ageAtWhichROITurnsPositive?: number | null,
    rankOfProgramByROI?: number | null,
    ROIIfStudentTakes5YearsToGraduate?: number | null,
    ROIIfStudentTakes6YearsToGraduate?: number | null,
    ROIIfStudentDropsBeforeGraduating?: number | null,
    ROIWeightedByInstitutionsCompletionOutcomes?: number | null,
    ROIBasedOnInstitutionsEducationRelatedSpending?: number | null,
    ROIBasedOnInstitutionsEducationRelatedSpending5years?: number | null,
    ROIBasedOnInstitutionsEducationRelatedSpending6Years?: number | null,
    ROIBasedOnInstitutionsEducationRelatedSpendingDrops?: number | null,
    ROIBasedOnInstitutionsEducationRelatedSpendingCompletionOutcomes?: number | null,
    estimatedEarnings23?: number | null,
    estimatedEarnings26?: number | null,
    estimatedEarnings29?: number | null,
    estimatedEarnings32?: number | null,
    estimatedEarnings35?: number | null,
    estimatedEarnings38?: number | null,
    estimatedEarnings41?: number | null,
    estimatedEarnings44?: number | null,
    estimatedEarnings47?: number | null,
    estimatedEarnings50?: number | null,
    estimatedEarnings53?: number | null,
    estimatedEarnings56?: number | null,
    estimatedEarnings59?: number | null,
    estimatedEarnings62?: number | null,
    estimatedCounterfactualEarnings19?: number | null,
    estimatedCounterfactualEarnings21?: number | null,
    estimatedCounterfactualEarnings23?: number | null,
    estimatedCounterfactualEarnings26?: number | null,
    estimatedCounterfactualEarnings29?: number | null,
    estimatedCounterfactualEarnings32?: number | null,
    estimatedCounterfactualEarnings35?: number | null,
    estimatedCounterfactualEarnings38?: number | null,
    estimatedCounterfactualEarnings41?: number | null,
    estimatedCounterfactualEarnings44?: number | null,
    estimatedCounterfactualEarnings47?: number | null,
    estimatedCounterfactualEarnings50?: number | null,
    estimatedCounterfactualEarnings53?: number | null,
    estimatedCounterfactualEarnings56?: number | null,
    estimatedCounterfactualEarnings59?: number | null,
    estimatedCounterfactualEarnings62?: number | null,
    resultsAvailableForAllSpecifications?: number | null,
    fourYearEducationRelatedSpending?: number | null,
    state?: string | null,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type OnDeleteROISubscription = {
  onDeleteROI?:  {
    __typename: "ROI",
    id: string,
    uniqueId?: string | null,
    institutionName?: string | null,
    programName?: string | null,
    unitId?: number | null,
    stateFIPSCode?: number | null,
    programCIPCode?: number | null,
    programCategory?: string | null,
    control?: string | null,
    carnegieClassification2015?: string | null,
    admissionsRate?: number | null,
    credentialLevel?: number | null,
    credentialLevelDescription?: string | null,
    collegeScorecardCohortCount?: number | null,
    annualNetTuitionCost?: number | null,
    fourYearNetTuitionCost?: number | null,
    annualEducationRelatedSpending?: number | null,
    shareOfStudentWhoGraduateIn4Years?: number | null,
    shareOfStudentWhoGraduateIn5Years?: number | null,
    shareOfStudentWhoGraduateIn6Years?: number | null,
    shareOfStudentWhoTransferOutIn6Years?: number | null,
    shareOfStudentWhoRemainIn6Years?: number | null,
    shareOfStudentWhoNoLongerEnrolledIn6Years?: number | null,
    absoluteIncreaseInLifetimeEarnings?: number | null,
    percentageIncreaseInLifetimeEarnings?: string | null,
    lifetimeReturnOnInvestmentROI?: number | null,
    ageAtWhichROITurnsPositive?: number | null,
    rankOfProgramByROI?: number | null,
    ROIIfStudentTakes5YearsToGraduate?: number | null,
    ROIIfStudentTakes6YearsToGraduate?: number | null,
    ROIIfStudentDropsBeforeGraduating?: number | null,
    ROIWeightedByInstitutionsCompletionOutcomes?: number | null,
    ROIBasedOnInstitutionsEducationRelatedSpending?: number | null,
    ROIBasedOnInstitutionsEducationRelatedSpending5years?: number | null,
    ROIBasedOnInstitutionsEducationRelatedSpending6Years?: number | null,
    ROIBasedOnInstitutionsEducationRelatedSpendingDrops?: number | null,
    ROIBasedOnInstitutionsEducationRelatedSpendingCompletionOutcomes?: number | null,
    estimatedEarnings23?: number | null,
    estimatedEarnings26?: number | null,
    estimatedEarnings29?: number | null,
    estimatedEarnings32?: number | null,
    estimatedEarnings35?: number | null,
    estimatedEarnings38?: number | null,
    estimatedEarnings41?: number | null,
    estimatedEarnings44?: number | null,
    estimatedEarnings47?: number | null,
    estimatedEarnings50?: number | null,
    estimatedEarnings53?: number | null,
    estimatedEarnings56?: number | null,
    estimatedEarnings59?: number | null,
    estimatedEarnings62?: number | null,
    estimatedCounterfactualEarnings19?: number | null,
    estimatedCounterfactualEarnings21?: number | null,
    estimatedCounterfactualEarnings23?: number | null,
    estimatedCounterfactualEarnings26?: number | null,
    estimatedCounterfactualEarnings29?: number | null,
    estimatedCounterfactualEarnings32?: number | null,
    estimatedCounterfactualEarnings35?: number | null,
    estimatedCounterfactualEarnings38?: number | null,
    estimatedCounterfactualEarnings41?: number | null,
    estimatedCounterfactualEarnings44?: number | null,
    estimatedCounterfactualEarnings47?: number | null,
    estimatedCounterfactualEarnings50?: number | null,
    estimatedCounterfactualEarnings53?: number | null,
    estimatedCounterfactualEarnings56?: number | null,
    estimatedCounterfactualEarnings59?: number | null,
    estimatedCounterfactualEarnings62?: number | null,
    resultsAvailableForAllSpecifications?: number | null,
    fourYearEducationRelatedSpending?: number | null,
    state?: string | null,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
  } | null,
};
